feature: adicionado middleware que checa inputs das rotas de criacão …
Kawamotus/cattus-nodejs pull request #5
Opened 2024-05-16 01:45 UTC by lealalves

- Adicionado middleware que verifica inputs necessários nas rotas de criação de documentos(/create)

2024-05-16 13:02 UTC, Gabrigom approved these changes
Não entendi 100% o checaCampos.js, mas parece ok.

2024-05-16 15:29 UTC, Kawamotus requested changes
conforme combinado, usaríamos apenas termos em inglês, por gentileza, resolva isso. Grato.

2024-05-16 15:54 UTC, lealalves commented
> conforme combinado, usaríamos apenas termos em inglês, por gentileza, resolva isso. Grato.

Você diz isso a respeito de nomes de funções, variaveis e arquivos?

2024-05-16 16:19 UTC, Kawamotus commented
Isso mesmo, por favor!

2024-05-17 22:03 UTC, lealalves commented
> Isso mesmo, por favor!

beleza!

2024-05-18 02:10 UTC, merged